version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Asia/Ho_Chi_Minh"
    open-pull-requests-limit: 15
    labels:
      - "dependencies"
      - "automerge"
      - "nuget"
    reviewers:
      - "realmg51-cpu"
    assignees:
      - "realmg51-cpu"
    # versioning-strategy: "auto"  # ❌ XÓA DÒNG NÀY
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
