name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: NtAI.sln
      Test_Project_Path: tests/NtAI.Tests/NtAI.Tests.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore dependencies
      run: dotnet restore $env:Solution_Name

    - name: Build solution
      run: msbuild $env:Solution_Name /p:Configuration=${{ matrix.configuration }}

    - name: Run tests
      run: dotnet test $env:Test_Project_Path --no-build --configuration ${{ matrix.configuration }}
